name: FarmerAI CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::592668326593:role/farmer-github-actions-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Docker Image
        run: |
          docker build -f backend/Dockerfile -t farmer-backend .

      - name: Build Frontend Docker Image
        run: |
          docker build -t farmer-frontend .

      - name: Tag Docker Images
        run: |
          docker tag farmer-backend:latest 592668326593.dkr.ecr.us-east-1.amazonaws.com/farmer-backend:latest
          docker tag farmer-frontend:latest 592668326593.dkr.ecr.us-east-1.amazonaws.com/farmer-frontend:latest

      - name: Push Images to ECR
        run: |
          docker push 592668326593.dkr.ecr.us-east-1.amazonaws.com/farmer-backend:latest
          docker push 592668326593.dkr.ecr.us-east-1.amazonaws.com/farmer-frontend:latest